# Generated by Django 3.0.4 on 2020-03-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0004_auto_20200320_1733'),
        ('poule', '0002_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.Poule')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='lobby.Team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='lobby.Team')),
            ],
        ),
    ]
