# Generated by Django 3.0.4 on 2020-03-21 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poule', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 13, 52, 0, 625607, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='game',
            name='result1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='result2',
            field=models.SmallIntegerField(null=True),
        ),
    ]
