# Generated by Django 3.0.4 on 2020-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poule', '0005_auto_20200321_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='result2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
