# Generated by Django 3.0.4 on 2020-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poule',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='poule',
            name='imageURL',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='imageURL',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
