# Generated by Django 3.0.4 on 2020-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_auto_20200325_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poule',
            name='description',
            field=models.TextField(blank=True, max_length=145),
        ),
        migrations.AlterField(
            model_name='poule',
            name='image',
            field=models.ImageField(default='poule_pics/default-poule.jpg', upload_to='poule_pics'),
        ),
        migrations.AlterField(
            model_name='poule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
