# Generated by Django 3.0.4 on 2020-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20200319_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poule',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='team',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='poule',
            name='image',
            field=models.ImageField(default='poule_pics/default.jpg', upload_to='poule_pics'),
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(default='sport_pics/default.jpg', upload_to='sport_pics'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='team_pics/default.jpg', upload_to='team_pics'),
        ),
    ]
